# Generated by Django 5.1 on 2025-03-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_sell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sell',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sell_price',
            new_name='sale_price',
        ),
    ]
