# Generated by Django 5.1 on 2025-03-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_sell_product_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='is_sale',
        ),
    ]
